server:
  port: 8081

spring:
  application:
    name: TaskMicroservice


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-uri:
      defaultZone: http://localhost:8761/eureka
