server:
  port: 8762
spring:
#  main:
#    web-application-type: reactive
  application:
    name: api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-uri:
      defaultZone: http://localhost:8761/eureka



#  cloud:
#    gateway:
#      routes:
#        - id: TaskMicroservice
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/serviceTasks/**


